# Dockerfile.prod

# Base image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . .

# Copy production environment variables
COPY .env.production .env

# Expose port 5000
EXPOSE 5000

# Run the app with a production-ready server
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
